### ISSUE TITLE
Error when running drug classification parser

### ISSUE THREAD

**Issue by lamnvcnsh** [ropensci/dbparser#121]
**Describe the bug**
An error raised when running drug_classification() as "Error: Argument 7 is a list, must contain atomic vectors"

**To Reproduce**
1. read_drugbank_xml_db('full_database.xml')
2. drug_class <- drug_classification()

Please help me to fix this bug.
Thank you very much.

**Comment by MohammedFCIS** [comment]
Hi @lamnvcnsh,
I could not reproduce the issue using dbparser 1.2.0 and DrugBank db 5.1.7 in Windows 10 environment.
May you please elaborate about error stack trace and your environment and used tools versions?
Thank you

**Comment by lamnvcnsh** [comment]
Thank @MohammedFCIS for your support.
I was run on the environment as bellow:
- OS: ubuntu 14.04 LTS server
- Platform: x86_64-pc-linux-gnu
- R version: 3.6.3 (2020-02-29)
- R studio version: 1.1.443
- dbparser version 1.2.0
- drug bank version: 5.1 exported-on 2020-07-02

**Comment by MohammedFCIS** [comment]
Hi @lamnvcnsh, you are welcome :).
That means we have two differences:
* R version
* Drugbank database version.
May you try to test with the latest version of both and try again.
Also, it would be more useful if you added the full stack trace.
Thank you

**Comment by MohammedFCIS** [comment]
Hi @lamnvcnsh , 
Any update regarding my last comment?
Thank you

**Comment by lamnvcnsh** [comment]
Sorry for the late reply, I am downloading a drug bank version 5.1.7 for checking. If have any update, I will let you know.

**Comment by lamnvcnsh** [comment]
Hi @MohammedFCIS ,
It raised the same error with the previous drugbank version.
I guest, R version is a cause for that. I will try later on.

**Comment by lamnvcnsh** [comment]
> Hi @lamnvcnsh,
> I could not reproduce the issue using dbparser 1.2.0 and DrugBank db 5.1.7 in Windows 10 environment.
> May you please elaborate about error stack trace and your environment and used tools versions?
> Thank you

Which R version are you using?

**Comment by lamnvcnsh** [comment]
Hi @MohammedFCIS ,
I installed the latest R, R studio on windows 10 and run_all_parser() worked perfectly.

Thank you very much.

**Comment by MohammedFCIS** [comment]
@lamnvcnsh 
That is great news. 
Please feel free to open another issue if you need more help.
Best Regards
