### ISSUE TITLE
Can I get 'SMILES' structure from 'dbparser'

### ISSUE THREAD

**Issue by mostafiz67** [ropensci/dbparser#124]
Hello, Yes, I am happy using `dbparser`. 

But, when I am doing some preprocessing and making my dataset, I found I need 'SMILES' structures (this is already included in the drugbank dataset). This 'dbparser' provides (UNII, CAS number, etc) but nowadays people need 'SMILES' structures.

Could you tell me, is there any parser in 'dbparser' I can get 'SMILES' structures of the drug.

**Comment by mostafiz67** [comment]
Hi, I found the SMILES structures. 

Thank you very much.

**Comment by mostafiz67** [comment]
After, parsing the `drugbank XML dataset` I have used the `dbparser` to get the `SMILES` structure. But, the structure is missing!

My code: 
```
library(tidyverse)
read_drugbank_xml_db("~/projects/drug_bank/full_database.xml")
drug_salts(save_csv = TRUE, override_csv = TRUE, csv_path="~/projects/drug_bank_csv")
drug_salts_df <- read.csv("~/projects/drug_bank_csv/drug_salts.csv")
```
After checking the `CSV` from `dtaframe` or `terminal` I am getting this info!

```
head -2 drug_salts.csv
drugbank-id,name,unii,cas-number,inchikey,average-mass,monoisotopic-mass,parent_key
DBSALT000105,Leuprolide acetate,37JNS02E7V,74381-53-6,YFDMUNOZURYOCP-XNHQSDQCSA-N,1269.473,1268.666591578,DB00007
```
Could you tell me do I have to change anything else?

**Comment by MohammedFCIS** [comment]
Hi @mostafiz67,
SMILES, among other properties, can be retrieved using ```drug_calc_prop``` parser.
Here is the detailed documentation about these properties https://mohammedfcis.github.io/dbdataset/reference/Calculated_Properties_Drug.html
In general, I recommend you to use this documentation https://docs.ropensci.org/dbparser/reference/ for parsers returned datasets details as ```dbdataset``` package is a data packaged from parsing DrugBank using ```dbparser```.
I hope that will help.
Best Regards,

**Comment by mostafiz67** [comment]
Hello @MohammedFCIS 

Thank you very much. I am getting this info from `drug_calc_prop`
```
kind,value,source,parent_key
logP,-0.76,ALOGPS,DB00006
```
Would you mind telling me, how can I get the `SMILES` from this result?

**Comment by MohammedFCIS** [comment]
Hi @mostafiz67 ,
You can get data using ```kind``` variable and filter by drugbank id in ```parent_key``` field as follow
```
calc <- read_csv("d:/DS Projects/dbdataset/data-raw/drug_calculated_properties.csv")
smiles <- calc %>% filter(kind == "SMILES")
```
Please review the documentation above for more useful information about these fields and their possible values.
Best Regards,

**Comment by mostafiz67** [comment]
Hi @MohammedFCIS 

Thank you very much for your kind support and reply.

Definitely, I will cite `dbparser` in my project report  :)

**Comment by mostafiz67** [comment]
Problem solved!

**Comment by MohammedFCIS** [comment]
@mostafiz67 , it is my pleasure 👍
