### ISSUE TITLE
remove RMariaDB as a dependency

### ISSUE THREAD

**Issue by MohammedFCIS** [ropensci/dbparser#129]

**Comment by mostafiz67** [comment]
Hi,

I am trying to install the package using `install.packages("dbparser")`, but getting error because of the `RMariaDB` dependency.

```
ERROR: dependency ‘RMariaDB’ is not available for package ‘dbparser’
* removing ‘/home/x2020fpt/R/x86_64-pc-linux-gnu-library/4.0/dbparser’

The downloaded source packages are in
	‘/tmp/RtmpcI18hb/downloaded_packages’
Warning messages:
1: In install.packages("dbparser") :
  installation of package ‘RMariaDB’ had non-zero exit status
2: In install.packages("dbparser") :
  installation of package ‘dbparser’ had non-zero exit status

```

Since this issue indicates that the `RMariaDB` has been removed as a dependency, why am I getting a dependency error? Or I am doing something wrong?

**Comment by MohammedFCIS** [comment]
Hi @mostafiz67 - what dbparser version you are trying to install?
Thank you

**Comment by mostafiz67** [comment]
I don't know the version. I just used `install.packages("dbparser")`
