### ISSUE TITLE
Fix pkgdown configuration for reference

### ISSUE THREAD

**Issue by maelle** [ropensci/dbparser#136]
Some topics are missing from the configuration file.

```r
 Error in check_missing_topics(rows, pkg) : 
   All topics must be included in reference index
• Missing topics: dbparser, drug_element, drug_element_options, get_drugbank_exported_date, get_drugbank_metadata, get_drugbank_version
```

Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

You can also use the `@keywords internal` tag and redocument for, say, the package manual page.

To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by maelle** [comment]
@MohammedFCIS

**Comment by MohammedFCIS** [comment]
Thanks @maelle - I am currently in a vacation. I shall fix this once I return. Thank you

**Comment by maelle** [comment]
Thank you, enjoy your time off! :sun_with_face:

**Comment by maelle** [comment]
@MohammedFCIS friendly reminder :smile_cat:

**Comment by MohammedFCIS** [comment]
Thank you @maelle. I will try to fix it ASAP.

**Comment by maelle** [comment]
@MohammedFCIS Happy New Year! Friendly reminder :smile_cat:

**Comment by MohammedFCIS** [comment]
Thanks @maelle, happy new year to you too :). 
I have an issue in creating branches and pushing to repo (it seems I have been removed from ropensci) may you please re-add me. Thank you

**Comment by maelle** [comment]
@MohammedFCIS, I've sent an invitation. Note that you will need to enable 2FA to accept it if you haven't done so yet.

For context https://ropensci.org/blog/2022/05/16/requiring-2fa-for-the-ropensci-github-organization/

**Comment by MohammedFCIS** [comment]
Thanks @maelle, I am able to create branches now, fix is under process.

**Comment by maelle** [comment]
Thank you!!
