### ISSUE TITLE
 extract drug's corresponding target actions info

### ISSUE THREAD

**Issue by penglimn** [ropensci/dbparser#137]
In this app, 

targets_actions(
  save_table = FALSE,
  save_csv = FALSE,
  csv_path = ".",
  override_csv = FALSE,
  database_connection = NULL
)

targets_actions function can extract targets and all of it's actions.

can this app only extract each drug's corresponding target actions info?

for example:
https://go.drugbank.com/drugs/DB00001

DB00001 only has one target: "1. [Prothrombin](https://go.drugbank.com/polypeptides/P00734)"
and this target's actions is "Inhibitor"

**Comment by MohammedFCIS** [comment]
Thanks @penglimn  for using dbparser. 
The answer is no, not in direct manner, you can filter the parsed dataframe using dplyr commands like any other data.frame as:
` targets_actions %>% dplyr::filter(parent_id == DB00001) `as I recall
