### ISSUE TITLE
Error upon loading Full Database (XML)

### ISSUE THREAD

**Issue by alizat** [ropensci/dbparser#157]
Hello,
After downloading the latest version of the complete DrugBank XML database (_Version 5.1.10_) from [here](https://go.drugbank.com/releases/latest), I attempted running the first 2 code snippets of [this vignette](https://cran.r-project.org/web/packages/dbparser/vignettes/dbparser.html) but was met with an error.

Below I include a shorter version of the code I ran that produces the same error.
```
## load dbparser package
library(dbparser)
library(dplyr)
library(ggplot2)
library(XML)

## parse data from XML and save it to memory
dvobj <- parseDrugBank(db_path = "full database.xml", drug_options = 'groups')

## load drugs data
drugs <- dvobj$drugs$general_information

## load drug groups data
drug_groups <- dvobj$drugs$groups

## view proportions of the different drug types for each drug group
drugs %>% 
  full_join(drug_groups, by = c('primary_key' = 'drugbank_id')) %>% 
  select(type, group) %>% 
  ggplot(aes(x = group, fill = type)) + 
  geom_bar() + 
  theme(legend.position = 'bottom') + 
  labs(x = 'Drug Group', 
       y = 'Quantity', 
       title = "Drug Type Distribution per Drug Group", 
       caption = "created by ggplot") + 
  coord_flip()
```

The error I get is
```
Error in `full_join()`:
! Join columns in `y` must be present in the data.
x Problem with `drugbank_id`.
Run `rlang::last_trace()` to see where the error occurred.
```

When I observed the `drug_groups` variable (which is a data frame), I found that it has two columns, `group` and `drugbank-id` (not `drugbank_id`). I then modified the full_join statement in the code above to `full_join(drug_groups, by = c('primary_key' = 'drugbank-id'))` and it worked fine.

It may be that the column name change from `drugbank_id` to `drugbank-id` has been introduced in the latest version of the DrugBank XML database. However, this is just a guess from my side.

<BR>

I am thinking there is more than one way to fix this issue:
- Fix any vignettes/tutorials code snippets that refer to `drugbank-id` need by replicating my fix above.
- Leave the vignettes/tutorials alone. In the `dbparser` package code, modify any occurrences of `drugbank-id` to be `drugbank_id` in parsed DrugBank data frames (Side note: I wonder if any other column names had their underscores replaced by dashes).

<BR>

Additional Info
 - OS: Windows
 - R version 4.1.3 (2022-03-10)
 - dbparser library version 2.0.1
 - XML library version 3.99-0.14

**Comment by MohammedFCIS** [comment]
Could not reproduce the issue with DB 5.1.11 and R v4.3.0
