### ISSUE TITLE
Drug-target gene, drug-drug indication mapping

### ISSUE THREAD

**Issue by Nobuyuki-Enzan** [ropensci/dbparser#159]
Hi,
I would like to create a table including drug, target gene (or protein e.g. Ensemble gene ID or Uniprot ID), and drug's indication (e.g. MONDO ID). After parsing xml data (version 5.1.10) using dbparser, I searched for these information, however, I could not find these. This xml file does not contain these information?
Best,
Nobuyuki

**Comment by MohammedFCIS** [comment]
@Nobuyuki-Enzan - all of these information and more can be obtained by running the following command:
```
dbobj <- dbparser::parseDrugBank("./drugbank_all_full_database.xml.zip",
                                 drug_options = dbparser::drug_node_options(),
                                 parse_salts = T,
                                 parse_products = T,
                                 references_options = dbparser::references_node_options(),
                                 cett_options = dbparser::cett_nodes_options())
```
Then you can view and work with `dbobj ` as list of all drugs tables
![image](https://github.com/ropensci/dbparser/assets/6381660/5a4b1a91-18dc-4a39-9354-599ae8f6a5a5)
![image](https://github.com/ropensci/dbparser/assets/6381660/286fb6f8-f905-450f-9f67-b28ad91f622c)
![image](https://github.com/ropensci/dbparser/assets/6381660/b4acb8b7-9af3-421b-b19d-d4aa063d49c4)


Also, the information is already parsed and can be used as normal R list object using [dbdataset package](https://github.com/interstellar-Consultation-Services/dbdataset)

**Comment by Nobuyuki-Enzan** [comment]
@MohammedFCIS MohammedFCIS
Thank you for your quick reply. I found drug-target protein information from dvobj$cett$targets$polypeptides$general_information thanks to you. However, I could not find INDICATION data, which is showed in "Associated Conditions" section in DrugBank Online.
![indication](https://github.com/ropensci/dbparser/assets/56494834/8f36dd3e-7d7d-43e6-8769-5f25380a92aa)

**Comment by MohammedFCIS** [comment]
@Nobuyuki-Enzan - is the following indication column in pharmacology table is what you are looking for?
![image](https://github.com/ropensci/dbparser/assets/6381660/d71bf5aa-6fd8-4b08-8ff5-684e57069f4e)

**Comment by Nobuyuki-Enzan** [comment]
@MohammedFCIS 
Unfortunately, no. What I want is more structured data. Something like "Edema" "Hypertension" "Primary aldosteronism" (please see the attached image). 
![indication](https://github.com/ropensci/dbparser/assets/56494834/ed938aad-b2ed-42f6-b748-d9cb1e165ef0)

**Comment by MohammedFCIS** [comment]
I am afraid that only that sample indication property is what available for the community users

![image](https://github.com/ropensci/dbparser/assets/6381660/043c35bd-fa0c-4aca-98ae-b80f0694ad46)
![image](https://github.com/ropensci/dbparser/assets/6381660/d7d10660-bf05-4a1f-bd6a-a5b9bdd9af83)

While structured indications is only available for drugbank+  subscribers (see [here](https://docs.drugbank.com/xml/#structured-indications)
![image](https://github.com/ropensci/dbparser/assets/6381660/b3436d90-3cc8-465a-901e-def9ff1fbce5)
and since dbparser is public package it deals only with public database.

I hope that would help you
Best regards,

**Comment by Nobuyuki-Enzan** [comment]
@MohammedFCIS
I understand. I appreciate your help.

**Comment by MohammedFCIS** [comment]
If you are drugbank subscriber, I can develop private dbparser version for your data as one of my company services.

**Comment by Nobuyuki-Enzan** [comment]
@MohammedFCIS 
So far, We are not drugbank subscriber. I talked to my PI, and if we subscribe DrugBank, please let me talk to you again.
