### ISSUE TITLE
Reactions tibble no info on enzymes that catalyze the reaction

### ISSUE THREAD

**Issue by AnjaConev** [ropensci/dbparser#165]
**Describe the bug**
When loading the data with "reactions" option and looking into the the tibbles I get there are "general_info" and "enzymes" but this info is separated and the information on which enzymes catalyze which reactions is lost.  

**To Reproduce**
1. Load the data (i.e., from drugmank.xml file)

 `db_parsed <- parseDrugBank(db_path = "./drugbank.xml", drug_options = c("reactions"))`
 
2. Check out the head of the reactions

`head(db_parsed$drugs$reactions)`

3. See that there are two tibbles:
     - general info with columns: sequence left_drugbank_id left_drugbank_name right_drugbank_id right_drugbank_name         drugbank_id
     - enzyme with: enzyme_id name uniprot_id
     
4. There is no way to reconstruct which enzymes are involved in which reactions from here

**Expected behavior**
Have info on enzymes within the general_info records

**Screenshots**
general_info 
![image](https://github.com/ropensci/dbparser/assets/7367905/88f738a2-7a1f-4ff6-88a4-f75e7a06887f)
enzymes
![image](https://github.com/ropensci/dbparser/assets/7367905/2e24c084-d27a-4538-ad6a-9c86a3c9ce63)

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 20.04

**Additional context**
When I looked into drug_reaction_node_parser.R it seems like you are not parsing the list of enzymes related to the reaction, it would be nice to have that info though!

**Comment by MohammedFCIS** [comment]
Thanks @AnjaConev for using dbparser.

- Since "Enzymes" has _alot_ of information, it has its own option to be parsed separately using `cett_options` as follow:
`dvobj <- parseDrugBank(db_path = "./drugbank_all_full_database.xml.zip", drug_options = c("reactions"), cett_options = c("enzymes"))`
- After that, you can get an additional sub-list for enzymes info
![image](https://github.com/ropensci/dbparser/assets/6381660/0ea62ece-a50c-4841-8454-51cad8e58099)
- You can see the enzymes in your image list below:
![image](https://github.com/ropensci/dbparser/assets/6381660/e6e11fbd-bc91-408c-a572-3ae9e62103e7)
- Then you can link between `dvobj[["cett"]][["enzymes"]][["general_information"]]` and `dvobj[["drugs"]][["reactions"]][["reactions_enzymes"]]` tables as any other normal `R` `data.frame`.
Please let me know if that would help or you have another question
Thank you

**Comment by AnjaConev** [comment]
Thank you for your reply! 

I am still a bit confused unfortunately.
What can I use to connect the enzyme general info with the reactions?
In particular, to know which enzyme from this list:
![image](https://github.com/ropensci/dbparser/assets/7367905/3ab47f70-d05a-48cb-ac77-307897a32a55)

In involved in the reactions from this list:
![image](https://github.com/ropensci/dbparser/assets/7367905/1115ea39-3d36-4fe5-8ed5-2af8bf2c4566)

What field to use to combine them?

**Comment by MohammedFCIS** [comment]
Hi @AnjaConev, please note the following:
- enzymes within reaction tag in DrugBank DB is optional and not always have data, please check below:
```reaction>
      <sequence>1</sequence>
      <left-element>
        <drugbank-id>DB00001</drugbank-id>
        <name>Lepirudin</name>
      </left-element>
      <right-element>
        <drugbank-id>DBMET03462</drugbank-id>
        <name>M1 (1-64)</name>
      </right-element>
      <enzymes/>
```
vs.
```
    <reaction>
      <sequence>1</sequence>
      <left-element>
        <drugbank-id>DB14583</drugbank-id>
        <name>Segesterone acetate</name>
      </left-element>
      <right-element>
        <drugbank-id>DBMET02127</drugbank-id>
        <name>5α-dihydrosegesterone acetate</name>
      </right-element>
      <enzymes>
        <enzyme>
          <drugbank-id>BE0002638</drugbank-id>
          <name>Cytochrome P450 3A4</name>
          <uniprot-id>P08684</uniprot-id>
        </enzyme>
      </enzymes>
    </reaction>
```
- All reactions related enzymes are stored in `reactions_enzymes` table
- To know which reaction is belonging to which enzyme check the following example for enzyme `BE0002638`
  - Get all that enzyme entries `enzyme <- dvobj$cett$enzymes$general_information %>% filter(enzyme_id == "BE0002638")`
  - Then get all reactions of these entries `enzyme_reactions <- dvobj$drugs$reactions$general_information %>% filter(drugbank_id %in% enzyme$drugbank_id)`
Please let me know if that would help, or you would another info
Thanks

**Comment by MohammedFCIS** [comment]
@AnjaConev - I am assuming the issue is resolved now. Please reopen if you feel otherwise. Thanks
