### ISSUE TITLE
Complete tutorial

### ISSUE THREAD

**Issue by miguecass** [ropensci/dbparser#170]
Hi,

I have recently adquire the XML for Drugbank 5.1.12 and I have been trying to use this package. However, the tutorial is missing many things and also the parsing function only takes 15 columns out of 55. For example what I want is to be able to obtain all the gene targets per drug and also their action on them. However, I do not see how to do it with this package.

Thanks in advance,

Miguel

**Comment by MohammedFCIS** [comment]
Hi @miguecass:
- There are different tutorials for the package [here](https://docs.ropensci.org/dbparser/), []here](https://docs.ropensci.org/dbparser/articles/dbparser.html) and [here](https://docs.ropensci.org/dbparser/reference/index.html). So, may you be more specific on the tutorial that you need?
- I did not quit understand what columns you are talking about here, but in general the parser function returns a `dvobject` which is an R list contains the parsed data based on user specifications (examples and more info in the above tutorials)
- You can get a drug targets by by filtering targets table by drugbank_id you need as same as any R data.frame and also their actions
![image](https://github.com/ropensci/dbparser/assets/6381660/df02150d-3b34-429d-a254-a6c3b8588b5f) 
![image](https://github.com/ropensci/dbparser/assets/6381660/7c4c5235-9f5c-49a2-96d1-19e2acaea5f6)
I hope that helps a little, and again please let me know what kind of tutorials you are seeking for
Best,
Mohammed
