### ISSUE TITLE
Python Wrapper for dbparser Package

### ISSUE THREAD

**Issue by alizat** [ropensci/dbparser#22]
It would be convenient for Python users who are interested in the dbparser package if there exists a Python wrapper for it. Such a wrapper may, for example, be uploaded to [Anaconda Cloud](https://anaconda.org/) or to something that is like *BioConductor* but within the Python universe (e.g. [BioPython](https://biopython.org/)).

**Comment by MohammedFCIS** [comment]
I think it will be an important feature to do that and to include it in the application note paper (even if it is not yet started 😈 ).
I would recommend creating a new repo for that with the same project and this one is dedicated to the R package. Let me know what you think @alizat .
