### ISSUE TITLE
Column size issue while importing into SQL Server

### ISSUE THREAD

**Issue by aycomp** [ropensci/dbparser#91]
**I am getting the following error while I am trying to import parsed DrugBank data into SQL Server**

Error: nanodbc/nanodbc.cpp:1617: 00000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The size (9436) given to the column 'pharmacodynamics' exceeds the maximum allowed for any data type (8000).  [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared.
<SQL> 'CREATE TABLE "drug" (
  "primary_key" varchar(255),
  "other_keys" varchar(255),
  "type" varchar(255),
  "created" DATE,
  "updated" DATE,
  "name" varchar(255),
  "description" varchar(6248),
  "cas_number" varchar(255),
  "unii" varchar(255),
  "average_mass" varchar(255),
  "monoisotopic_mass" varchar(255),
  "state" varchar(255),
  "groups_count" INT,
  "articles_count" INT,
  "books_count" INT,
  "links_count" INT,
  "synthesis_reference" varchar(845),
  "indication" varchar(3517),
  "pharmacodynamics" varchar(9436),
  "mechanism_of_action" varchar(7088),
  "metabolism" varchar(2825),
  "absorption" varchar(4002),
  "half_life" varchar(1133),
  "protein_binding" varchar(677),
  "rou

**A screenshot of my RStudio window containing code and the error is as following:**

![1](https://user-images.githubusercontent.com/25276436/77119535-b4659580-6a47-11ea-9c21-9d3100bd3059.png)

**Additional Information:**
 - OS: Linux (Ubuntu 18.04.4 LTS) <X64>
-  Microsoft SQL Server 2019 (X64)  Developer Edition
-  RStudio
-  DrugBank version 5.1.5

**Comment by MohammedFCIS** [comment]
Thank you @aycomp for submitting that issue. I will work on it ASAP. 
Happy Friday :)

**Comment by aycomp** [comment]
Happy Friday to you too

**Comment by aycomp** [comment]
While I was trying to import an older version of DrugBank xml file (version 5-1-4), I got a similar error also. 
I am adding the screenshot of this error too by thinking it would be useful

![1](https://user-images.githubusercontent.com/25276436/77156987-8ddc4480-6ab1-11ea-83f5-8cf4d6ee2e5e.png)

Thank you,
Ayse

**Comment by MohammedFCIS** [comment]
@aycomp, kindly use github setup to update dbparser and test . Thank you
`library(devtools)
devtools::install_github("ropensci/dbparser")`

**Comment by aycomp** [comment]
Hi Mohammed,

it is working now , Thank you !

Ayse
